name = "thekevshot"
[observability]
[observability.logs]
enabled = true
invocation_logs = false

[vars]
NUXT_CMS_BASE_URL="https://cms.thekevshot.com"
NUXT_MEDIA_BASE_URL="https://cms.thekevshot.com"
NUXT_IMAGE_DOMAINS="thekevshot.com"
NUXT_PUBLIC_GTAG_ID="G-9JSDM5R8DD"

# resend setup
NUXT_CONTACT_TO_ADDRESS="kyrodriguez97@gmail.com"
NUXT_CONTACT_FROM_ADDRESS="noreply@thekevshot.com"

NUXT_PUBLIC_TURNSTILE_SITE_KEY="0x4AAAAAAChpBMoMlQBHzL3-"