name: Compress images
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: calibreapp/webp-optimizer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Compress Images
        uses: calibreapp/webp-optimizer@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
